### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by joepke** [Antfield-Creations/Antfield-Creations.github.io#1]
@reinvantveer Mooi werk! Binnenkort naar Het Valkhof. De links naar 'art' en 'software' werken niet bij mij; `.md` i.p.v. `.html`?

**Comment by reinvantveer** [comment]
Ha die Joep! Dank zal het eens even proberen te fixen.

**Comment by reinvantveer** [comment]
Je bedoelt die groene knoppen naar ik aanneem? Kan het niet helemaal volgen, zojuist geprobeerd in FF, Chromium, Chrome op mobiel, allen verwijzen goed door naar https://antfield.nl/pages/software.html c.q. http://antfield.nl/pages/art.html. Heb je een hard refresh gedaan? Welke browser gebruik je?

**Comment by joepke** [comment]
Ah, ik snap heb, ik keek verkeerd! Ik probeerde het op https://github.com/Antfield-Creations/Antfield-Creations.github.io, dus binnen GitHub zelf. Groene knopjes op de antfield.nl werken perfect 👍

Issue mag achter slot, grendel en in de prullenbak.
